package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int legajoEmpleado;
     private Sucursal sucursal;
     private String usuario;
     private String contrasenia;
     private int dniEmpleado;
     private String nombreEmpleado;
     private String apellidoEmpleado;
     private String domicilioEmpleado;
     private String telefonoEmpleado;
     private String emailEmpleado;
     private char sexoEmpleado;
     private Date fechaNacimientoEmpleado;
     private int codigoPostalEmpleado;
     private String cargoEmpleado;
     private String departamentoEmpleado;
     private Date fechaIngresoEmpresa;
     private BigDecimal sueldoEmpleado;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set facturas = new HashSet(0);
     private Set estados = new HashSet(0);
     private Gerente gerente;

    public Empleado() {
    }

	
    public Empleado(int legajoEmpleado, Sucursal sucursal, String usuario, String contrasenia, int dniEmpleado, String nombreEmpleado, String apellidoEmpleado, String domicilioEmpleado, char sexoEmpleado, Date fechaNacimientoEmpleado, int codigoPostalEmpleado, String cargoEmpleado, String departamentoEmpleado, Date fechaIngresoEmpresa, BigDecimal sueldoEmpleado, Date fechaRegistro, Date fechaModificacion) {
        this.legajoEmpleado = legajoEmpleado;
        this.sucursal = sucursal;
        this.usuario = usuario;
        this.contrasenia = contrasenia;
        this.dniEmpleado = dniEmpleado;
        this.nombreEmpleado = nombreEmpleado;
        this.apellidoEmpleado = apellidoEmpleado;
        this.domicilioEmpleado = domicilioEmpleado;
        this.sexoEmpleado = sexoEmpleado;
        this.fechaNacimientoEmpleado = fechaNacimientoEmpleado;
        this.codigoPostalEmpleado = codigoPostalEmpleado;
        this.cargoEmpleado = cargoEmpleado;
        this.departamentoEmpleado = departamentoEmpleado;
        this.fechaIngresoEmpresa = fechaIngresoEmpresa;
        this.sueldoEmpleado = sueldoEmpleado;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Empleado(int legajoEmpleado, Sucursal sucursal, String usuario, String contrasenia, int dniEmpleado, String nombreEmpleado, String apellidoEmpleado, String domicilioEmpleado, String telefonoEmpleado, String emailEmpleado, char sexoEmpleado, Date fechaNacimientoEmpleado, int codigoPostalEmpleado, String cargoEmpleado, String departamentoEmpleado, Date fechaIngresoEmpresa, BigDecimal sueldoEmpleado, Date fechaRegistro, Date fechaModificacion, Set facturas, Set estados, Gerente gerente) {
       this.legajoEmpleado = legajoEmpleado;
       this.sucursal = sucursal;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.dniEmpleado = dniEmpleado;
       this.nombreEmpleado = nombreEmpleado;
       this.apellidoEmpleado = apellidoEmpleado;
       this.domicilioEmpleado = domicilioEmpleado;
       this.telefonoEmpleado = telefonoEmpleado;
       this.emailEmpleado = emailEmpleado;
       this.sexoEmpleado = sexoEmpleado;
       this.fechaNacimientoEmpleado = fechaNacimientoEmpleado;
       this.codigoPostalEmpleado = codigoPostalEmpleado;
       this.cargoEmpleado = cargoEmpleado;
       this.departamentoEmpleado = departamentoEmpleado;
       this.fechaIngresoEmpresa = fechaIngresoEmpresa;
       this.sueldoEmpleado = sueldoEmpleado;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.facturas = facturas;
       this.estados = estados;
       this.gerente = gerente;
    }
   
    public int getLegajoEmpleado() {
        return this.legajoEmpleado;
    }
    
    public void setLegajoEmpleado(int legajoEmpleado) {
        this.legajoEmpleado = legajoEmpleado;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public int getDniEmpleado() {
        return this.dniEmpleado;
    }
    
    public void setDniEmpleado(int dniEmpleado) {
        this.dniEmpleado = dniEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getApellidoEmpleado() {
        return this.apellidoEmpleado;
    }
    
    public void setApellidoEmpleado(String apellidoEmpleado) {
        this.apellidoEmpleado = apellidoEmpleado;
    }
    public String getDomicilioEmpleado() {
        return this.domicilioEmpleado;
    }
    
    public void setDomicilioEmpleado(String domicilioEmpleado) {
        this.domicilioEmpleado = domicilioEmpleado;
    }
    public String getTelefonoEmpleado() {
        return this.telefonoEmpleado;
    }
    
    public void setTelefonoEmpleado(String telefonoEmpleado) {
        this.telefonoEmpleado = telefonoEmpleado;
    }
    public String getEmailEmpleado() {
        return this.emailEmpleado;
    }
    
    public void setEmailEmpleado(String emailEmpleado) {
        this.emailEmpleado = emailEmpleado;
    }
    public char getSexoEmpleado() {
        return this.sexoEmpleado;
    }
    
    public void setSexoEmpleado(char sexoEmpleado) {
        this.sexoEmpleado = sexoEmpleado;
    }
    public Date getFechaNacimientoEmpleado() {
        return this.fechaNacimientoEmpleado;
    }
    
    public void setFechaNacimientoEmpleado(Date fechaNacimientoEmpleado) {
        this.fechaNacimientoEmpleado = fechaNacimientoEmpleado;
    }
    public int getCodigoPostalEmpleado() {
        return this.codigoPostalEmpleado;
    }
    
    public void setCodigoPostalEmpleado(int codigoPostalEmpleado) {
        this.codigoPostalEmpleado = codigoPostalEmpleado;
    }
    public String getCargoEmpleado() {
        return this.cargoEmpleado;
    }
    
    public void setCargoEmpleado(String cargoEmpleado) {
        this.cargoEmpleado = cargoEmpleado;
    }
    public String getDepartamentoEmpleado() {
        return this.departamentoEmpleado;
    }
    
    public void setDepartamentoEmpleado(String departamentoEmpleado) {
        this.departamentoEmpleado = departamentoEmpleado;
    }
    public Date getFechaIngresoEmpresa() {
        return this.fechaIngresoEmpresa;
    }
    
    public void setFechaIngresoEmpresa(Date fechaIngresoEmpresa) {
        this.fechaIngresoEmpresa = fechaIngresoEmpresa;
    }
    public BigDecimal getSueldoEmpleado() {
        return this.sueldoEmpleado;
    }
    
    public void setSueldoEmpleado(BigDecimal sueldoEmpleado) {
        this.sueldoEmpleado = sueldoEmpleado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }
    public Gerente getGerente() {
        return this.gerente;
    }
    
    public void setGerente(Gerente gerente) {
        this.gerente = gerente;
    }




}


