package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private EstadoId id;
     private Empleado empleado;
     private Paquete paquete;
     private Sucursal sucursal;
     private TipoEstado tipoEstado;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Estado() {
    }

	
    public Estado(EstadoId id, Paquete paquete, TipoEstado tipoEstado, Date fechaRegistro, Date fechaModificacion) {
        this.id = id;
        this.paquete = paquete;
        this.tipoEstado = tipoEstado;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Estado(EstadoId id, Empleado empleado, Paquete paquete, Sucursal sucursal, TipoEstado tipoEstado, Date fechaRegistro, Date fechaModificacion) {
       this.id = id;
       this.empleado = empleado;
       this.paquete = paquete;
       this.sucursal = sucursal;
       this.tipoEstado = tipoEstado;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public EstadoId getId() {
        return this.id;
    }
    
    public void setId(EstadoId id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Paquete getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Paquete paquete) {
        this.paquete = paquete;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public TipoEstado getTipoEstado() {
        return this.tipoEstado;
    }
    
    public void setTipoEstado(TipoEstado tipoEstado) {
        this.tipoEstado = tipoEstado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


