package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1



/**
 * EstadoId generated by hbm2java
 */
public class EstadoId  implements java.io.Serializable {


     private char tipoEstadoId;
     private int paqueteId;

    public EstadoId() {
    }

    public EstadoId(char tipoEstadoId, int paqueteId) {
       this.tipoEstadoId = tipoEstadoId;
       this.paqueteId = paqueteId;
    }
   
    public char getTipoEstadoId() {
        return this.tipoEstadoId;
    }
    
    public void setTipoEstadoId(char tipoEstadoId) {
        this.tipoEstadoId = tipoEstadoId;
    }
    public int getPaqueteId() {
        return this.paqueteId;
    }
    
    public void setPaqueteId(int paqueteId) {
        this.paqueteId = paqueteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstadoId) ) return false;
		 EstadoId castOther = ( EstadoId ) other; 
         
		 return (this.getTipoEstadoId()==castOther.getTipoEstadoId())
 && (this.getPaqueteId()==castOther.getPaqueteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTipoEstadoId();
         result = 37 * result + this.getPaqueteId();
         return result;
   }   


}


