package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int paqueteId;
     private Empleado empleado;
     private Paquete paquete;
     private Sucursal sucursal;
     private int numeroFactura;
     private char tipoFactura;
     private BigDecimal montoTotalFactura;
     private String clienteFactura;
     private Integer dniCliente;
     private String nombreCliente;
     private String apellidoCliente;
     private String direcionCliente;
     private String telefonoCliente;
     private Integer codigoPostalCliente;
     private String emailCliente;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Factura() {
    }

	
    public Factura(Paquete paquete, int numeroFactura, char tipoFactura, Date fechaRegistro, Date fechaModificacion) {
        this.paquete = paquete;
        this.numeroFactura = numeroFactura;
        this.tipoFactura = tipoFactura;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Factura(Empleado empleado, Paquete paquete, Sucursal sucursal, int numeroFactura, char tipoFactura, BigDecimal montoTotalFactura, String clienteFactura, Integer dniCliente, String nombreCliente, String apellidoCliente, String direcionCliente, String telefonoCliente, Integer codigoPostalCliente, String emailCliente, Date fechaRegistro, Date fechaModificacion) {
       this.empleado = empleado;
       this.paquete = paquete;
       this.sucursal = sucursal;
       this.numeroFactura = numeroFactura;
       this.tipoFactura = tipoFactura;
       this.montoTotalFactura = montoTotalFactura;
       this.clienteFactura = clienteFactura;
       this.dniCliente = dniCliente;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.direcionCliente = direcionCliente;
       this.telefonoCliente = telefonoCliente;
       this.codigoPostalCliente = codigoPostalCliente;
       this.emailCliente = emailCliente;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getPaqueteId() {
        return this.paqueteId;
    }
    
    public void setPaqueteId(int paqueteId) {
        this.paqueteId = paqueteId;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Paquete getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Paquete paquete) {
        this.paquete = paquete;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public char getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(char tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public BigDecimal getMontoTotalFactura() {
        return this.montoTotalFactura;
    }
    
    public void setMontoTotalFactura(BigDecimal montoTotalFactura) {
        this.montoTotalFactura = montoTotalFactura;
    }
    public String getClienteFactura() {
        return this.clienteFactura;
    }
    
    public void setClienteFactura(String clienteFactura) {
        this.clienteFactura = clienteFactura;
    }
    public Integer getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(Integer dniCliente) {
        this.dniCliente = dniCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getDirecionCliente() {
        return this.direcionCliente;
    }
    
    public void setDirecionCliente(String direcionCliente) {
        this.direcionCliente = direcionCliente;
    }
    public String getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(String telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    public Integer getCodigoPostalCliente() {
        return this.codigoPostalCliente;
    }
    
    public void setCodigoPostalCliente(Integer codigoPostalCliente) {
        this.codigoPostalCliente = codigoPostalCliente;
    }
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


