package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Gerente generated by hbm2java
 */
public class Gerente  implements java.io.Serializable {


     private int legajoGerente;
     private Empleado empleado;
     private Sucursal sucursal;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public Gerente() {
    }

    public Gerente(Empleado empleado, Sucursal sucursal, Date fechaRegistro, Date fechaModificacion) {
       this.empleado = empleado;
       this.sucursal = sucursal;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getLegajoGerente() {
        return this.legajoGerente;
    }
    
    public void setLegajoGerente(int legajoGerente) {
        this.legajoGerente = legajoGerente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


