package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int localidadId;
     private Provincia provincia;
     private String localidad;
     private Set sucursals = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(int localidadId, Provincia provincia) {
        this.localidadId = localidadId;
        this.provincia = provincia;
    }
    public Localidad(int localidadId, Provincia provincia, String localidad, Set sucursals) {
       this.localidadId = localidadId;
       this.provincia = provincia;
       this.localidad = localidad;
       this.sucursals = sucursals;
    }
   
    public int getLocalidadId() {
        return this.localidadId;
    }
    
    public void setLocalidadId(int localidadId) {
        this.localidadId = localidadId;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }




}


