package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int paisId;
     private String pais;
     private Set provincias = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int paisId) {
        this.paisId = paisId;
    }
    public Pais(int paisId, String pais, Set provincias) {
       this.paisId = paisId;
       this.pais = pais;
       this.provincias = provincias;
    }
   
    public int getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(int paisId) {
        this.paisId = paisId;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


