package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PaquetesPorTransporte generated by hbm2java
 */
public class PaquetesPorTransporte  implements java.io.Serializable {


     private PaquetesPorTransporteId id;
     private Paquete paquete;
     private Transporte transporte;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public PaquetesPorTransporte() {
    }

    public PaquetesPorTransporte(PaquetesPorTransporteId id, Paquete paquete, Transporte transporte, Date fechaRegistro, Date fechaModificacion) {
       this.id = id;
       this.paquete = paquete;
       this.transporte = transporte;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public PaquetesPorTransporteId getId() {
        return this.id;
    }
    
    public void setId(PaquetesPorTransporteId id) {
        this.id = id;
    }
    public Paquete getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Paquete paquete) {
        this.paquete = paquete;
    }
    public Transporte getTransporte() {
        return this.transporte;
    }
    
    public void setTransporte(Transporte transporte) {
        this.transporte = transporte;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


