package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int provinciaId;
     private Pais pais;
     private String provincia;
     private Set localidads = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int provinciaId, Pais pais) {
        this.provinciaId = provinciaId;
        this.pais = pais;
    }
    public Provincia(int provinciaId, Pais pais, String provincia, Set localidads) {
       this.provinciaId = provinciaId;
       this.pais = pais;
       this.provincia = provincia;
       this.localidads = localidads;
    }
   
    public int getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(int provinciaId) {
        this.provinciaId = provinciaId;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Set getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set localidads) {
        this.localidads = localidads;
    }




}


