package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region  implements java.io.Serializable {


     private int regionId;
     private String nombre;
     private int desdeKm;
     private int hastaKm;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set servicios = new HashSet(0);

    public Region() {
    }

	
    public Region(int regionId, int desdeKm, int hastaKm, Date fechaRegistro, Date fechaModificacion) {
        this.regionId = regionId;
        this.desdeKm = desdeKm;
        this.hastaKm = hastaKm;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Region(int regionId, String nombre, int desdeKm, int hastaKm, Date fechaRegistro, Date fechaModificacion, Set servicios) {
       this.regionId = regionId;
       this.nombre = nombre;
       this.desdeKm = desdeKm;
       this.hastaKm = hastaKm;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.servicios = servicios;
    }
   
    public int getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(int regionId) {
        this.regionId = regionId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getDesdeKm() {
        return this.desdeKm;
    }
    
    public void setDesdeKm(int desdeKm) {
        this.desdeKm = desdeKm;
    }
    public int getHastaKm() {
        return this.hastaKm;
    }
    
    public void setHastaKm(int hastaKm) {
        this.hastaKm = hastaKm;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set servicios) {
        this.servicios = servicios;
    }




}


