package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private char roleId;
     private String roleNombre;
     private String roleDescripcion;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set logins = new HashSet(0);

    public Role() {
    }

	
    public Role(char roleId, Date fechaRegistro, Date fechaModificacion) {
        this.roleId = roleId;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Role(char roleId, String roleNombre, String roleDescripcion, Date fechaRegistro, Date fechaModificacion, Set logins) {
       this.roleId = roleId;
       this.roleNombre = roleNombre;
       this.roleDescripcion = roleDescripcion;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.logins = logins;
    }
   
    public char getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(char roleId) {
        this.roleId = roleId;
    }
    public String getRoleNombre() {
        return this.roleNombre;
    }
    
    public void setRoleNombre(String roleNombre) {
        this.roleNombre = roleNombre;
    }
    public String getRoleDescripcion() {
        return this.roleDescripcion;
    }
    
    public void setRoleDescripcion(String roleDescripcion) {
        this.roleDescripcion = roleDescripcion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }




}


