package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta  implements java.io.Serializable {


     private RutaId id;
     private Sucursal sucursalBySecursalDestino;
     private Sucursal sucursalBySucursalOrigen;
     private Double distanciaRuta;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set rutasPorTransportes = new HashSet(0);

    public Ruta() {
    }

	
    public Ruta(RutaId id, Sucursal sucursalBySecursalDestino, Sucursal sucursalBySucursalOrigen, Date fechaRegistro, Date fechaModificacion) {
        this.id = id;
        this.sucursalBySecursalDestino = sucursalBySecursalDestino;
        this.sucursalBySucursalOrigen = sucursalBySucursalOrigen;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Ruta(RutaId id, Sucursal sucursalBySecursalDestino, Sucursal sucursalBySucursalOrigen, Double distanciaRuta, Date fechaRegistro, Date fechaModificacion, Set rutasPorTransportes) {
       this.id = id;
       this.sucursalBySecursalDestino = sucursalBySecursalDestino;
       this.sucursalBySucursalOrigen = sucursalBySucursalOrigen;
       this.distanciaRuta = distanciaRuta;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.rutasPorTransportes = rutasPorTransportes;
    }
   
    public RutaId getId() {
        return this.id;
    }
    
    public void setId(RutaId id) {
        this.id = id;
    }
    public Sucursal getSucursalBySecursalDestino() {
        return this.sucursalBySecursalDestino;
    }
    
    public void setSucursalBySecursalDestino(Sucursal sucursalBySecursalDestino) {
        this.sucursalBySecursalDestino = sucursalBySecursalDestino;
    }
    public Sucursal getSucursalBySucursalOrigen() {
        return this.sucursalBySucursalOrigen;
    }
    
    public void setSucursalBySucursalOrigen(Sucursal sucursalBySucursalOrigen) {
        this.sucursalBySucursalOrigen = sucursalBySucursalOrigen;
    }
    public Double getDistanciaRuta() {
        return this.distanciaRuta;
    }
    
    public void setDistanciaRuta(Double distanciaRuta) {
        this.distanciaRuta = distanciaRuta;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getRutasPorTransportes() {
        return this.rutasPorTransportes;
    }
    
    public void setRutasPorTransportes(Set rutasPorTransportes) {
        this.rutasPorTransportes = rutasPorTransportes;
    }




}


