package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RutasPorTransporte generated by hbm2java
 */
public class RutasPorTransporte  implements java.io.Serializable {


     private RutasPorTransporteId id;
     private Ruta ruta;
     private Transporte transporte;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public RutasPorTransporte() {
    }

    public RutasPorTransporte(RutasPorTransporteId id, Ruta ruta, Transporte transporte, Date fechaRegistro, Date fechaModificacion) {
       this.id = id;
       this.ruta = ruta;
       this.transporte = transporte;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public RutasPorTransporteId getId() {
        return this.id;
    }
    
    public void setId(RutasPorTransporteId id) {
        this.id = id;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Transporte getTransporte() {
        return this.transporte;
    }
    
    public void setTransporte(Transporte transporte) {
        this.transporte = transporte;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


