package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1



/**
 * RutaId generated by hbm2java
 */
public class RutaId  implements java.io.Serializable {


     private int sucursalOrigen;
     private int secursalDestino;

    public RutaId() {
    }

    public RutaId(int sucursalOrigen, int secursalDestino) {
       this.sucursalOrigen = sucursalOrigen;
       this.secursalDestino = secursalDestino;
    }
   
    public int getSucursalOrigen() {
        return this.sucursalOrigen;
    }
    
    public void setSucursalOrigen(int sucursalOrigen) {
        this.sucursalOrigen = sucursalOrigen;
    }
    public int getSecursalDestino() {
        return this.secursalDestino;
    }
    
    public void setSecursalDestino(int secursalDestino) {
        this.secursalDestino = secursalDestino;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RutaId) ) return false;
		 RutaId castOther = ( RutaId ) other; 
         
		 return (this.getSucursalOrigen()==castOther.getSucursalOrigen())
 && (this.getSecursalDestino()==castOther.getSecursalDestino());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSucursalOrigen();
         result = 37 * result + this.getSecursalDestino();
         return result;
   }   


}


