package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int servicioId;
     private Region region;
     private String nombreServicio;
     private String descServicio;
     private BigDecimal precioBasico;
     private Integer kgBasico;
     private Integer kgPorExceso;
     private Integer estampillasPorExceso;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set paquetes = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(int servicioId, Region region, String nombreServicio, Date fechaRegistro, Date fechaModificacion) {
        this.servicioId = servicioId;
        this.region = region;
        this.nombreServicio = nombreServicio;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Servicio(int servicioId, Region region, String nombreServicio, String descServicio, BigDecimal precioBasico, Integer kgBasico, Integer kgPorExceso, Integer estampillasPorExceso, Date fechaRegistro, Date fechaModificacion, Set paquetes) {
       this.servicioId = servicioId;
       this.region = region;
       this.nombreServicio = nombreServicio;
       this.descServicio = descServicio;
       this.precioBasico = precioBasico;
       this.kgBasico = kgBasico;
       this.kgPorExceso = kgPorExceso;
       this.estampillasPorExceso = estampillasPorExceso;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.paquetes = paquetes;
    }
   
    public int getServicioId() {
        return this.servicioId;
    }
    
    public void setServicioId(int servicioId) {
        this.servicioId = servicioId;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getNombreServicio() {
        return this.nombreServicio;
    }
    
    public void setNombreServicio(String nombreServicio) {
        this.nombreServicio = nombreServicio;
    }
    public String getDescServicio() {
        return this.descServicio;
    }
    
    public void setDescServicio(String descServicio) {
        this.descServicio = descServicio;
    }
    public BigDecimal getPrecioBasico() {
        return this.precioBasico;
    }
    
    public void setPrecioBasico(BigDecimal precioBasico) {
        this.precioBasico = precioBasico;
    }
    public Integer getKgBasico() {
        return this.kgBasico;
    }
    
    public void setKgBasico(Integer kgBasico) {
        this.kgBasico = kgBasico;
    }
    public Integer getKgPorExceso() {
        return this.kgPorExceso;
    }
    
    public void setKgPorExceso(Integer kgPorExceso) {
        this.kgPorExceso = kgPorExceso;
    }
    public Integer getEstampillasPorExceso() {
        return this.estampillasPorExceso;
    }
    
    public void setEstampillasPorExceso(Integer estampillasPorExceso) {
        this.estampillasPorExceso = estampillasPorExceso;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Set paquetes) {
        this.paquetes = paquetes;
    }




}


