package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int sucursalId;
     private Localidad localidad;
     private String nombreSucursal;
     private boolean prioritarioPermitido;
     private boolean urgentePermitido;
     private String direccionSucursal;
     private String telefonoSucursal;
     private int codigoPostalSucursal;
     private String horarioDeAtencion;
     private double latitudeSucursal;
     private double longitudeSucursal;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set empleados = new HashSet(0);
     private Set paquetesForDestinoPaquete = new HashSet(0);
     private Set paquetesForOrigenPaquete = new HashSet(0);
     private Set rutasForSecursalDestino = new HashSet(0);
     private Set facturas = new HashSet(0);
     private Set rutasForSucursalOrigen = new HashSet(0);
     private Set estados = new HashSet(0);
     private Set gerentes = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(int sucursalId, Localidad localidad, boolean prioritarioPermitido, boolean urgentePermitido, String direccionSucursal, int codigoPostalSucursal, double latitudeSucursal, double longitudeSucursal, Date fechaRegistro, Date fechaModificacion) {
        this.sucursalId = sucursalId;
        this.localidad = localidad;
        this.prioritarioPermitido = prioritarioPermitido;
        this.urgentePermitido = urgentePermitido;
        this.direccionSucursal = direccionSucursal;
        this.codigoPostalSucursal = codigoPostalSucursal;
        this.latitudeSucursal = latitudeSucursal;
        this.longitudeSucursal = longitudeSucursal;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Sucursal(int sucursalId, Localidad localidad, String nombreSucursal, boolean prioritarioPermitido, boolean urgentePermitido, String direccionSucursal, String telefonoSucursal, int codigoPostalSucursal, String horarioDeAtencion, double latitudeSucursal, double longitudeSucursal, Date fechaRegistro, Date fechaModificacion, Set empleados, Set paquetesForDestinoPaquete, Set paquetesForOrigenPaquete, Set rutasForSecursalDestino, Set facturas, Set rutasForSucursalOrigen, Set estados, Set gerentes) {
       this.sucursalId = sucursalId;
       this.localidad = localidad;
       this.nombreSucursal = nombreSucursal;
       this.prioritarioPermitido = prioritarioPermitido;
       this.urgentePermitido = urgentePermitido;
       this.direccionSucursal = direccionSucursal;
       this.telefonoSucursal = telefonoSucursal;
       this.codigoPostalSucursal = codigoPostalSucursal;
       this.horarioDeAtencion = horarioDeAtencion;
       this.latitudeSucursal = latitudeSucursal;
       this.longitudeSucursal = longitudeSucursal;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.empleados = empleados;
       this.paquetesForDestinoPaquete = paquetesForDestinoPaquete;
       this.paquetesForOrigenPaquete = paquetesForOrigenPaquete;
       this.rutasForSecursalDestino = rutasForSecursalDestino;
       this.facturas = facturas;
       this.rutasForSucursalOrigen = rutasForSucursalOrigen;
       this.estados = estados;
       this.gerentes = gerentes;
    }
   
    public int getSucursalId() {
        return this.sucursalId;
    }
    
    public void setSucursalId(int sucursalId) {
        this.sucursalId = sucursalId;
    }
    public Localidad getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(Localidad localidad) {
        this.localidad = localidad;
    }
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public boolean isPrioritarioPermitido() {
        return this.prioritarioPermitido;
    }
    
    public void setPrioritarioPermitido(boolean prioritarioPermitido) {
        this.prioritarioPermitido = prioritarioPermitido;
    }
    public boolean isUrgentePermitido() {
        return this.urgentePermitido;
    }
    
    public void setUrgentePermitido(boolean urgentePermitido) {
        this.urgentePermitido = urgentePermitido;
    }
    public String getDireccionSucursal() {
        return this.direccionSucursal;
    }
    
    public void setDireccionSucursal(String direccionSucursal) {
        this.direccionSucursal = direccionSucursal;
    }
    public String getTelefonoSucursal() {
        return this.telefonoSucursal;
    }
    
    public void setTelefonoSucursal(String telefonoSucursal) {
        this.telefonoSucursal = telefonoSucursal;
    }
    public int getCodigoPostalSucursal() {
        return this.codigoPostalSucursal;
    }
    
    public void setCodigoPostalSucursal(int codigoPostalSucursal) {
        this.codigoPostalSucursal = codigoPostalSucursal;
    }
    public String getHorarioDeAtencion() {
        return this.horarioDeAtencion;
    }
    
    public void setHorarioDeAtencion(String horarioDeAtencion) {
        this.horarioDeAtencion = horarioDeAtencion;
    }
    public double getLatitudeSucursal() {
        return this.latitudeSucursal;
    }
    
    public void setLatitudeSucursal(double latitudeSucursal) {
        this.latitudeSucursal = latitudeSucursal;
    }
    public double getLongitudeSucursal() {
        return this.longitudeSucursal;
    }
    
    public void setLongitudeSucursal(double longitudeSucursal) {
        this.longitudeSucursal = longitudeSucursal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getPaquetesForDestinoPaquete() {
        return this.paquetesForDestinoPaquete;
    }
    
    public void setPaquetesForDestinoPaquete(Set paquetesForDestinoPaquete) {
        this.paquetesForDestinoPaquete = paquetesForDestinoPaquete;
    }
    public Set getPaquetesForOrigenPaquete() {
        return this.paquetesForOrigenPaquete;
    }
    
    public void setPaquetesForOrigenPaquete(Set paquetesForOrigenPaquete) {
        this.paquetesForOrigenPaquete = paquetesForOrigenPaquete;
    }
    public Set getRutasForSecursalDestino() {
        return this.rutasForSecursalDestino;
    }
    
    public void setRutasForSecursalDestino(Set rutasForSecursalDestino) {
        this.rutasForSecursalDestino = rutasForSecursalDestino;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getRutasForSucursalOrigen() {
        return this.rutasForSucursalOrigen;
    }
    
    public void setRutasForSucursalOrigen(Set rutasForSucursalOrigen) {
        this.rutasForSucursalOrigen = rutasForSucursalOrigen;
    }
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }
    public Set getGerentes() {
        return this.gerentes;
    }
    
    public void setGerentes(Set gerentes) {
        this.gerentes = gerentes;
    }




}


