package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transporte generated by hbm2java
 */
public class Transporte  implements java.io.Serializable {


     private int transporteId;
     private Camion camion;
     private Double distanciaTotalTransporte;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set paquetesPorTransportes = new HashSet(0);
     private Set rutasPorTransportes = new HashSet(0);

    public Transporte() {
    }

	
    public Transporte(int transporteId, Camion camion, Date fechaRegistro, Date fechaModificacion) {
        this.transporteId = transporteId;
        this.camion = camion;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Transporte(int transporteId, Camion camion, Double distanciaTotalTransporte, Date fechaRegistro, Date fechaModificacion, Set paquetesPorTransportes, Set rutasPorTransportes) {
       this.transporteId = transporteId;
       this.camion = camion;
       this.distanciaTotalTransporte = distanciaTotalTransporte;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.paquetesPorTransportes = paquetesPorTransportes;
       this.rutasPorTransportes = rutasPorTransportes;
    }
   
    public int getTransporteId() {
        return this.transporteId;
    }
    
    public void setTransporteId(int transporteId) {
        this.transporteId = transporteId;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public Double getDistanciaTotalTransporte() {
        return this.distanciaTotalTransporte;
    }
    
    public void setDistanciaTotalTransporte(Double distanciaTotalTransporte) {
        this.distanciaTotalTransporte = distanciaTotalTransporte;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getPaquetesPorTransportes() {
        return this.paquetesPorTransportes;
    }
    
    public void setPaquetesPorTransportes(Set paquetesPorTransportes) {
        this.paquetesPorTransportes = paquetesPorTransportes;
    }
    public Set getRutasPorTransportes() {
        return this.rutasPorTransportes;
    }
    
    public void setRutasPorTransportes(Set rutasPorTransportes) {
        this.rutasPorTransportes = rutasPorTransportes;
    }




}


