package edu.utnfrre.appcstpf.Pojo;
// Generated 09/06/2015 21:03:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private String contrasenia;
     private int dniUsuario;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String domicilioUsuario;
     private String telefonoUsuario;
     private String emailUsuario;
     private char sexoUsuario;
     private Date fechaNacimientoUsuario;
     private Integer codigoPostalUsuario;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set paquetes = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String contrasenia, int dniUsuario, String nombreUsuario, String apellidoUsuario, String domicilioUsuario, String emailUsuario, char sexoUsuario, Date fechaNacimientoUsuario, Date fechaRegistro, Date fechaModificacion) {
        this.usuario = usuario;
        this.contrasenia = contrasenia;
        this.dniUsuario = dniUsuario;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.domicilioUsuario = domicilioUsuario;
        this.emailUsuario = emailUsuario;
        this.sexoUsuario = sexoUsuario;
        this.fechaNacimientoUsuario = fechaNacimientoUsuario;
        this.fechaRegistro = fechaRegistro;
        this.fechaModificacion = fechaModificacion;
    }
    public Usuario(String usuario, String contrasenia, int dniUsuario, String nombreUsuario, String apellidoUsuario, String domicilioUsuario, String telefonoUsuario, String emailUsuario, char sexoUsuario, Date fechaNacimientoUsuario, Integer codigoPostalUsuario, Date fechaRegistro, Date fechaModificacion, Set paquetes) {
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.dniUsuario = dniUsuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.domicilioUsuario = domicilioUsuario;
       this.telefonoUsuario = telefonoUsuario;
       this.emailUsuario = emailUsuario;
       this.sexoUsuario = sexoUsuario;
       this.fechaNacimientoUsuario = fechaNacimientoUsuario;
       this.codigoPostalUsuario = codigoPostalUsuario;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.paquetes = paquetes;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public int getDniUsuario() {
        return this.dniUsuario;
    }
    
    public void setDniUsuario(int dniUsuario) {
        this.dniUsuario = dniUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public String getDomicilioUsuario() {
        return this.domicilioUsuario;
    }
    
    public void setDomicilioUsuario(String domicilioUsuario) {
        this.domicilioUsuario = domicilioUsuario;
    }
    public String getTelefonoUsuario() {
        return this.telefonoUsuario;
    }
    
    public void setTelefonoUsuario(String telefonoUsuario) {
        this.telefonoUsuario = telefonoUsuario;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public char getSexoUsuario() {
        return this.sexoUsuario;
    }
    
    public void setSexoUsuario(char sexoUsuario) {
        this.sexoUsuario = sexoUsuario;
    }
    public Date getFechaNacimientoUsuario() {
        return this.fechaNacimientoUsuario;
    }
    
    public void setFechaNacimientoUsuario(Date fechaNacimientoUsuario) {
        this.fechaNacimientoUsuario = fechaNacimientoUsuario;
    }
    public Integer getCodigoPostalUsuario() {
        return this.codigoPostalUsuario;
    }
    
    public void setCodigoPostalUsuario(Integer codigoPostalUsuario) {
        this.codigoPostalUsuario = codigoPostalUsuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Set paquetes) {
        this.paquetes = paquetes;
    }




}


